const DEFAULT_CONFIG={
  lessons:'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_LKSMUYj7ehGgazL1-sujxiznaWetrYLHPGTRJ9UEHJxYf7r9rNeU5I6Gqenm6e3gQafDA_sZKbKC/pub?gid=0&single=true&output=csv',
  vocab:'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_LKSMUYj7ehGgazL1-sujxiznaWetrYLHPGTRJ9UEHJxYf7r9rNeU5I6Gqenm6e3gQafDA_sZKbKC/pub?gid=754782420&single=true&output=csv',
  grammar:'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_LKSMUYj7ehGgazL1-sujxiznaWetrYLHPGTRJ9UEHJxYf7r9rNeU5I6Gqenm6e3gQafDA_sZKbKC/pub?gid=1482161321&single=true&output=csv'
};
const KEYS={local:'koreanReviewLocal_v4',config:'koreanReviewConfig_v4',theme:'koreanReviewTheme_v1'};
const THEMES={
  celadon:{name:'Celadon',bg:'#edf3ee',panel:'#ffffff',ink:'#1b2b22',accent:'#365446',accent2:'#4c7a66',soft:'#e7efe9',warm:'#c9683c',gold:'#d89a3a',line:'#ccd8cf'},
  ink:{name:'Ink',bg:'#f2f2f0',panel:'#ffffff',ink:'#1e2525',accent:'#253f46',accent2:'#4e6b73',soft:'#e8edef',warm:'#9f5b42',gold:'#b48c39',line:'#d4d8d7'},
  peach:{name:'Peach',bg:'#fbf1e9',panel:'#fffdfb',ink:'#352721',accent:'#7d4e43',accent2:'#9a6b5d',soft:'#f5e3d7',warm:'#c56c4f',gold:'#c79a45',line:'#ead6c8'},
  lilac:{name:'Lilac',bg:'#f2eff8',panel:'#ffffff',ink:'#2f2938',accent:'#554769',accent2:'#75658a',soft:'#ebe5f2',warm:'#a75f72',gold:'#b08b43',line:'#dad2e3'}
};
const BASICS=[
  {title:'1. Hangul syllable blocks',short:'Korean letters are arranged into square syllable blocks.',body:'Most syllables are built from an initial consonant (초성) + vowel (중성), with an optional final consonant (종성 / 받침). The letters are not written in a straight line like English; they combine into one block.',formula:'초성 + 중성 (+ 종성) → 한 글자'},
  {title:'2. Basic sentence order',short:'A common default is Subject – Object – Verb.',body:'Korean often places the verb or adjective at the end. The subject may be omitted when it is obvious from context. Instead of relying only on word order, Korean uses particles to mark grammatical roles.',formula:'저는 + 한국어를 + 공부해요. → I + Korean + study.'},
  {title:'3. Topic / subject / object particles',short:'Particles tell you what a noun is doing in the sentence.',body:'은/는 often marks a topic or contrast. 이/가 often marks the grammatical subject or new/focused information. 을/를 marks the object. Their exact nuance depends on context, so beginners should learn them through example sentences rather than one English translation.',formula:'저는 학생이에요. / 비가 와요. / 책을 읽어요.'},
  {title:'4. Politeness endings',short:'The ending of a sentence carries social meaning.',body:'Two beginner-friendly styles are 해요체 (-아요/어요) and the more formal 합니다체 (-ㅂ니다/습니다). Start with one style consistently, then learn when different styles are used.',formula:'가요 / 먹어요 / 합니다 / 먹습니다'},
  {title:'5. Native Korean vs Sino-Korean numbers',short:'Korean uses two number systems.',body:'The system depends on what you count: hours and many counters often use Native Korean numbers, while dates, money, phone numbers, minutes and many measurements often use Sino-Korean numbers.',formula:'한 시 (1 o’clock) / 일 분 (1 minute)'}
];

let local=readJSON(KEYS.local,{lessons:[],vocab:[],grammar:[],progress:{},favorites:[]});
if(!Array.isArray(local.favorites)) local.favorites=[];
let config=readJSON(KEYS.config,DEFAULT_CONFIG);
let themeState=readJSON(KEYS.theme,{preset:'celadon',custom:null});
let shared={lessons:[],vocab:[],grammar:[]},repoPack={lessons:[],vocab:[],grammar:[]};
let allLessons=[],allVocab=[],allGrammar=[],currentLesson='all',currentView='today',browseType='all',browseQuery='',reviewMode='srs',reviewQueue=[],reviewIndex=0,quizType='mixed',quiz=null;
let loadStats={repo:0,lessons:0,vocab:0,grammar:0,errors:[]};

function readJSON(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
function writeJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function today(){return new Date().toISOString().slice(0,10)}
function addDays(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function lessonKey(s){s=String(s||'').trim();const m=s.match(/(?:lesson\s*)?(\d+)/i);if(m)return 'lesson-'+m[1];return s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9가-힣]+/g,'-').replace(/^-|-$/g,'')||'unsorted'}
function normalizeCsvUrl(url){url=String(url||'').trim();if(!url)return '';try{if(url.includes('/pubhtml'))url=url.replace('/pubhtml','/pub');if(url.includes('/pub?')){const u=new URL(url);u.searchParams.set('single','true');u.searchParams.set('output','csv');return u.toString()}}catch{}return url}
function isFav(id){return local.favorites.includes(id)}
function toggleFav(id){local.favorites=isFav(id)?local.favorites.filter(x=>x!==id):[...local.favorites,id];writeJSON(KEYS.local,local);renderCurrent()}
function progressFor(id){return local.progress[id]||{reps:0,interval:0,ease:2.5,due:today()}}
function isDue(id){return progressFor(id).due<=today()}
function oneExample(s){const a=String(s||'').split(/\r?\n|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);return a.length?a[Math.floor(Math.random()*a.length)]:''}

function applyTheme(){let t=themeState.custom||THEMES[themeState.preset]||THEMES.celadon;const root=document.documentElement;root.style.setProperty('--bg',t.bg);root.style.setProperty('--panel',t.panel);root.style.setProperty('--ink',t.ink);root.style.setProperty('--accent',t.accent);root.style.setProperty('--accent-2',t.accent2||t.accent);root.style.setProperty('--accent-soft',t.soft||'#e7efe9');root.style.setProperty('--warm',t.warm||'#c9683c');root.style.setProperty('--gold',t.gold||'#d89a3a');root.style.setProperty('--line',t.line||'#ccd8cf')}
applyTheme();

const headerAlias={lesson:'lesson','lesson name':'lesson',name:'name',korean:'korean','korean word':'korean',word:'korean',term:'korean',pos:'pos','part of speech':'pos',meaning:'meaning','english meaning':'meaning',definition:'meaning',origin:'origin','word origin':'origin',etymology:'origin',example:'example','example sentence':'example',examples:'example',image:'image','image url':'image',pattern:'pattern','grammar pattern':'pattern',grammar:'pattern',explain:'explain',explanation:'explain','grammar explanation':'explain'};
function cleanHeader(h){h=String(h||'').replace(/^\ufeff/,'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');return headerAlias[h]||h}
async function fetchCsv(url,label){const res=await fetch(normalizeCsvUrl(url),{cache:'no-store'});if(!res.ok)throw new Error(`${label}: HTTP ${res.status}`);const text=await res.text();const parsed=Papa.parse(text,{header:true,skipEmptyLines:'greedy',transformHeader:cleanHeader});return parsed.data.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[cleanHeader(k),String(v??'').trim()]))) }
async function fetchRepoPack(){try{const r=await fetch(`shared-content.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('No repository content pack');const data=await r.json();repoPack={lessons:data.lessons||[],vocab:data.vocab||[],grammar:data.grammar||[]};loadStats.repo=(repoPack.vocab.length+repoPack.grammar.length)}catch(e){repoPack={lessons:[],vocab:[],grammar:[]}}}
async function loadShared(){loadStats={repo:0,lessons:0,vocab:0,grammar:0,errors:[]};document.getElementById('syncStatus').textContent='Loading shared library…';await fetchRepoPack();const urls={lessons:config.lessons||config.lessonsUrl||DEFAULT_CONFIG.lessons,vocab:config.vocab||config.vocabUrl||DEFAULT_CONFIG.vocab,grammar:config.grammar||config.grammarUrl||DEFAULT_CONFIG.grammar};config=urls;writeJSON(KEYS.config,config);const res=await Promise.allSettled([fetchCsv(urls.lessons,'Lessons'),fetchCsv(urls.vocab,'Vocabulary'),fetchCsv(urls.grammar,'Grammar')]);const L=res[0].status==='fulfilled'?res[0].value:(loadStats.errors.push(res[0].reason.message),[]);const V=res[1].status==='fulfilled'?res[1].value:(loadStats.errors.push(res[1].reason.message),[]);const G=res[2].status==='fulfilled'?res[2].value:(loadStats.errors.push(res[2].reason.message),[]);
 shared.lessons=L.filter(r=>r.name||r.lesson).map(r=>{const name=r.name||r.lesson;return{id:lessonKey(name),name,shared:true}});
 shared.vocab=V.filter(r=>r.korean).map(r=>({id:'sv-'+lessonKey(r.lesson)+'-'+lessonKey(r.korean),lessonId:lessonKey(r.lesson),lessonName:r.lesson||'Unsorted',korean:r.korean,pos:r.pos||'',meaning:r.meaning||'',origin:r.origin||'',example:r.example||'',image:r.image||'',shared:true}));
 shared.grammar=G.filter(r=>r.pattern).map(r=>({id:'sg-'+lessonKey(r.lesson)+'-'+lessonKey(r.pattern),lessonId:lessonKey(r.lesson),lessonName:r.lesson||'Unsorted',pattern:r.pattern,explain:r.explain||'',example:r.example||'',shared:true}));
 loadStats.lessons=shared.lessons.length;loadStats.vocab=shared.vocab.length;loadStats.grammar=shared.grammar.length;merge();renderAll();}

function normalizeRepo(){const lessons=(repoPack.lessons||[]).map(l=>typeof l==='string'?{name:l}:l).filter(l=>l.name).map(l=>({id:l.id||lessonKey(l.name),name:l.name,shared:true,source:'repo'}));const vocab=(repoPack.vocab||[]).filter(v=>v.korean).map(v=>({id:v.id||'rv-'+lessonKey(v.lesson||v.lessonName)+'-'+lessonKey(v.korean),lessonId:v.lessonId||lessonKey(v.lesson||v.lessonName),lessonName:v.lesson||v.lessonName||'Unsorted',korean:v.korean,pos:v.pos||'',meaning:v.meaning||'',origin:v.origin||'',example:Array.isArray(v.example)?v.example.join('\n'):(v.example||''),image:v.image||'',shared:true,source:'repo'}));const grammar=(repoPack.grammar||[]).filter(g=>g.pattern).map(g=>({id:g.id||'rg-'+lessonKey(g.lesson||g.lessonName)+'-'+lessonKey(g.pattern),lessonId:g.lessonId||lessonKey(g.lesson||g.lessonName),lessonName:g.lesson||g.lessonName||'Unsorted',pattern:g.pattern,explain:g.explain||g.explanation||'',example:Array.isArray(g.example)?g.example.join('\n'):(g.example||''),shared:true,source:'repo'}));return{lessons,vocab,grammar}}
function merge(){const rp=normalizeRepo();const lessonMap=new Map();[...rp.lessons,...shared.lessons,...local.lessons].forEach(l=>lessonMap.set(l.id,l));const dedupe=(arr,keyFn)=>{const m=new Map();arr.forEach(x=>m.set(keyFn(x),x));return [...m.values()]};allVocab=dedupe([...shared.vocab,...rp.vocab,...local.vocab],v=>`${v.lessonId}::${v.korean}`);allGrammar=dedupe([...shared.grammar,...rp.grammar,...local.grammar],g=>`${g.lessonId}::${g.pattern}`);[...allVocab,...allGrammar].forEach(x=>{if(!lessonMap.has(x.lessonId))lessonMap.set(x.lessonId,{id:x.lessonId,name:x.lessonName||'Unsorted',shared:true})});allLessons=[...lessonMap.values()].sort((a,b)=>{const na=+(a.name.match(/\d+/)||[999])[0],nb=+(b.name.match(/\d+/)||[999])[0];return na-nb||a.name.localeCompare(b.name)})}

function renderAll(){renderSync();renderLessons();renderCurrent()}
function renderSync(){const s=document.getElementById('syncStatus');const total=allVocab.length+allGrammar.length;const sheetTotal=loadStats.vocab+loadStats.grammar;s.innerHTML=`<b>${total}</b> shared + personal items<br>${sheetTotal} from Sheets${loadStats.repo?` · ${loadStats.repo} from repo pack`:''}${loadStats.errors.length?'<br><span style="color:#ffd2c8">Some sources failed</span>':''}`;document.getElementById('banner').innerHTML=loadStats.errors.length?`<div class="banner">Some shared sources did not load. The site is still usable with the content that loaded. Open <b>Advanced</b> to inspect or change the links.</div>`:''}
function lessonCount(id){return allVocab.filter(v=>v.lessonId===id).length+allGrammar.filter(g=>g.lessonId===id).length}
function renderLessons(){const nav=document.getElementById('lessonList');nav.innerHTML='';const make=(id,name,count)=>{const b=document.createElement('button');b.className='lesson-link'+(currentLesson===id?' active':'');b.innerHTML=`<span>${esc(name)}</span><span class="lesson-count">${count}</span>`;b.onclick=()=>{currentLesson=id;renderAll()};nav.appendChild(b)};make('all','All lessons',allVocab.length+allGrammar.length);allLessons.forEach(l=>make(l.id,l.name,lessonCount(l.id)))}

function switchView(view){currentView=view;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));const titles={today:['Today','A small plan for your next Korean study session.'],learn:['Learn basics','Build a mental model before memorizing details.'],browse:['Browse','Search, compare, and save what matters.'],review:['Flashcards','Review with progressively longer intervals.'],quiz:['Quiz','Practice recognition without turning grammar into a wall of text.']};document.getElementById('pageTitle').textContent=titles[view][0];document.getElementById('pageSubtitle').textContent=titles[view][1];renderCurrent()}
function renderCurrent(){if(currentView==='today')renderToday();if(currentView==='learn')renderLearn();if(currentView==='browse')renderBrowse();if(currentView==='review')renderReview();if(currentView==='quiz')renderQuizShell()}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));

function currentPool(){return{vocab:allVocab.filter(v=>currentLesson==='all'||v.lessonId===currentLesson),grammar:allGrammar.filter(g=>currentLesson==='all'||g.lessonId===currentLesson)}}
function renderToday(){const el=document.getElementById('view-today');const pool=currentPool();const allCards=[...pool.vocab.map(v=>({id:v.id})),...pool.grammar.map(g=>({id:g.id}))];const due=allCards.filter(c=>isDue(c.id)).length;const mastered=allCards.filter(c=>progressFor(c.id).interval>=14).length;const pct=allCards.length?Math.round(mastered/allCards.length*100):0;const label=currentLesson==='all'?'all lessons':(allLessons.find(l=>l.id===currentLesson)?.name||'this lesson');el.innerHTML=`
<div class="grid stats">
 <div class="stat-card"><div class="stat-value">${due}</div><div class="stat-label">cards due today</div></div>
 <div class="stat-card"><div class="stat-value">${pool.vocab.length}</div><div class="stat-label">vocabulary in ${esc(label)}</div></div>
 <div class="stat-card"><div class="stat-value">${pool.grammar.length}</div><div class="stat-label">grammar points</div></div>
 <div class="stat-card"><div class="stat-value">${pct}%</div><div class="stat-label">mastery estimate</div></div>
</div>
<div class="section-title"><h2>Suggested next step</h2></div>
<div class="quick-actions">
 <button class="quick-card" onclick="switchView('review')"><b>${due?`Review ${due} due cards`:'Browse flashcards'}</b><span class="muted">Start small; you can stop after one round.</span></button>
 <button class="quick-card" onclick="switchView('quiz')"><b>Do a short quiz</b><span class="muted">Mixed vocab + grammar, one question at a time.</span></button>
 <button class="quick-card" onclick="switchView('learn')"><b>Learn the foundations</b><span class="muted">Useful if Hangul structure or sentence order still feels fuzzy.</span></button>
</div>
<div class="section-title"><h2>Progress</h2><span class="muted grow">${mastered} of ${allCards.length} cards at 14+ day interval</span></div>
<div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>
<div class="section-title"><h2>Saved for later</h2></div>
${renderFavoritePreview()}`}
function renderFavoritePreview(){const ids=new Set(local.favorites);const items=[...allVocab.filter(v=>ids.has(v.id)).slice(0,4),...allGrammar.filter(g=>ids.has(g.id)).slice(0,4)];if(!items.length)return '<div class="empty">Star a word or grammar point in Browse and it will appear here.</div>';return `<div class="list">${items.slice(0,6).map(x=>x.korean?vocabEntry(x):grammarEntry(x)).join('')}</div>`}

function renderLearn(){const el=document.getElementById('view-learn');el.innerHTML=`<div class="learn-grid"><div>${BASICS.map((b,i)=>`<div class="topic-card" style="margin-bottom:12px"><h3>${esc(b.title)}</h3><p>${esc(b.short)}</p><details${i===0?' open':''}><summary>See explanation</summary><p style="margin-top:8px">${esc(b.body)}</p><div class="formula">${esc(b.formula)}</div></details></div>`).join('')}</div><div><div class="topic-card"><h3>Hangul block builder</h3><p>Pick the three positions to see how Korean syllables are composed.</p><div class="composer"><label class="muted">Initial<select id="choSel"></select></label><label class="muted">Vowel<select id="jungSel"></select></label><label class="muted">Final<select id="jongSel"></select></label></div><div class="syllable-result" id="syllableResult">가</div><div class="hangul-note" id="syllableNote">ㄱ + ㅏ → 가</div></div><div class="topic-card" style="margin-top:12px"><h3>Beginner path</h3><p>Recommended order: Hangul blocks → pronunciation basics → sentence order → particles → polite endings → textbook lesson review. This prevents the site from feeling like a pile of disconnected cards.</p></div></div></div>`;setupComposer()}
function setupComposer(){const cho=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];const jung=['ㅏ','ㅐ','ㅑ','ㅒ','ㅓ','ㅔ','ㅕ','ㅖ','ㅗ','ㅘ','ㅙ','ㅚ','ㅛ','ㅜ','ㅝ','ㅞ','ㅟ','ㅠ','ㅡ','ㅢ','ㅣ'];const jong=['','ㄱ','ㄲ','ㄳ','ㄴ','ㄵ','ㄶ','ㄷ','ㄹ','ㄺ','ㄻ','ㄼ','ㄽ','ㄾ','ㄿ','ㅀ','ㅁ','ㅂ','ㅄ','ㅅ','ㅆ','ㅇ','ㅈ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];const fill=(id,a)=>{document.getElementById(id).innerHTML=a.map((x,i)=>`<option value="${i}">${x||'—'}</option>`).join('')};fill('choSel',cho);fill('jungSel',jung);fill('jongSel',jong);document.getElementById('jungSel').value='0';['choSel','jungSel','jongSel'].forEach(id=>document.getElementById(id).onchange=compose);compose();function compose(){const ci=+document.getElementById('choSel').value,vi=+document.getElementById('jungSel').value,fi=+document.getElementById('jongSel').value;const syll=String.fromCharCode(0xAC00+(ci*21+vi)*28+fi);document.getElementById('syllableResult').textContent=syll;document.getElementById('syllableNote').textContent=`${cho[ci]} + ${jung[vi]}${fi?` + ${jong[fi]}`:''} → ${syll}`}}

function vocabEntry(v){return `<div class="entry">${v.image?`<img class="thumb" src="${esc(v.image)}" onerror="this.style.display='none'">`:''}<div class="entry-body"><div><span class="entry-title">${esc(v.korean)}</span><span class="entry-meta">${esc(v.pos)}</span> <button class="btn small ghost" onclick="speak(${JSON.stringify(v.korean)})">🔊</button> <button class="btn small ghost" onclick="openDict(${JSON.stringify(v.korean)})">Naver ↗</button></div><div class="entry-meaning">${esc(v.meaning)}</div>${v.origin?`<div class="entry-origin">${esc(v.origin)}</div>`:''}${v.example?`<details class="details"><summary>Example sentence</summary><div class="entry-example">${esc(oneExample(v.example))}</div></details>`:''}</div><div class="entry-actions"><button class="star ${isFav(v.id)?'on':''}" title="Save" onclick="toggleFav('${v.id}')">★</button>${!v.shared?`<button class="btn small ghost" onclick="editV('${v.id}')">Edit</button>`:''}</div></div>`}
function grammarEntry(g){return `<div class="entry"><div class="entry-body"><div class="entry-title">${esc(g.pattern)}</div><details class="details"><summary>Explanation</summary><div class="entry-meaning" style="margin-top:7px">${esc(g.explain)}</div>${g.example?`<div class="entry-example">${esc(oneExample(g.example))}</div>`:''}</details></div><div class="entry-actions"><button class="star ${isFav(g.id)?'on':''}" title="Save" onclick="toggleFav('${g.id}')">★</button>${!g.shared?`<button class="btn small ghost" onclick="editG('${g.id}')">Edit</button>`:''}</div></div>`}
function renderBrowse(){const el=document.getElementById('view-browse');const pool=currentPool();let items=[];if(browseType!=='grammar')items.push(...pool.vocab.map(x=>({...x,_type:'v'})));if(browseType!=='vocab')items.push(...pool.grammar.map(x=>({...x,_type:'g'})));if(browseType==='favorites')items=items.filter(x=>isFav(x.id));const q=browseQuery.trim().toLowerCase();if(q)items=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q));el.innerHTML=`<div class="browse-tools"><input id="browseSearch" value="${esc(browseQuery)}" placeholder="Search Korean, meaning, origin, or grammar…"><button class="btn primary" id="addVocabBtn">+ Vocabulary</button><button class="btn ghost" id="addGrammarBtn">+ Grammar</button></div><div class="chip-row" style="margin-bottom:14px">${[['all','All'],['vocab','Vocabulary'],['grammar','Grammar'],['favorites','★ Saved']].map(([k,n])=>`<button class="chip ${browseType===k?'active':''}" data-filter="${k}">${n}</button>`).join('')}</div><div class="list">${items.length?items.map(x=>x._type==='v'?vocabEntry(x):grammarEntry(x)).join(''):'<div class="empty">Nothing matches this filter yet.</div>'}</div>`;document.getElementById('browseSearch').oninput=e=>{browseQuery=e.target.value;renderBrowse()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{browseType=b.dataset.filter;renderBrowse()});document.getElementById('addVocabBtn').onclick=()=>openVocab();document.getElementById('addGrammarBtn').onclick=()=>openGrammar()}

function reviewPool(){const pool=currentPool();return[...pool.vocab.map(x=>({...x,_type:'v'})),...pool.grammar.map(x=>({...x,_type:'g'}))]}
function renderReview(){const el=document.getElementById('view-review');let pool=reviewPool();reviewQueue=reviewMode==='srs'?pool.filter(x=>isDue(x.id)):pool;if(reviewIndex>=reviewQueue.length)reviewIndex=0;el.innerHTML=`<div class="flash-wrap"><div class="chip-row"><button class="chip ${reviewMode==='srs'?'active':''}" id="modeSrs">Due today</button><button class="chip ${reviewMode==='browse'?'active':''}" id="modeBrowse">Browse all</button></div><div class="muted" id="reviewProgress"></div><div class="flash" id="flash"><div class="flash-inner"><div class="face front" id="frontFace"></div><div class="face back" id="backFace"></div></div></div><div class="rate-row" id="rateRow"></div><div class="review-nav" id="reviewNav"></div></div>`;document.getElementById('modeSrs').onclick=()=>{reviewMode='srs';reviewIndex=0;renderReview()};document.getElementById('modeBrowse').onclick=()=>{reviewMode='browse';reviewIndex=0;renderReview()};renderCard()}
function renderCard(){const f=document.getElementById('frontFace'),b=document.getElementById('backFace'),prog=document.getElementById('reviewProgress'),rate=document.getElementById('rateRow'),nav=document.getElementById('reviewNav');if(!reviewQueue.length){f.innerHTML='<div class="big">Nothing due 🎉</div><div class="small">Switch to Browse all or choose another lesson.</div>';b.innerHTML='';prog.textContent='0 cards';rate.innerHTML='';nav.innerHTML='';return}const c=reviewQueue[reviewIndex];prog.textContent=`${reviewIndex+1} / ${reviewQueue.length}`;if(c._type==='v'){f.innerHTML=`${c.image?`<img class="thumb" style="width:95px;height:95px;margin-bottom:14px" src="${esc(c.image)}">`:''}<div class="big">${esc(c.korean)}</div><div class="small">${esc(c.pos)}</div>`;b.innerHTML=`<div class="big" style="font-size:20px">${esc(c.meaning)}</div>${c.origin?`<div class="entry-origin">${esc(c.origin)}</div>`:''}${c.example?`<div class="example">${esc(oneExample(c.example))}</div>`:''}`}else{f.innerHTML=`<div class="big" style="font-size:23px">${esc(c.pattern)}</div><div class="small">Tap to reveal the explanation</div>`;b.innerHTML=`<div style="font-size:15px;line-height:1.6">${esc(c.explain)}</div>${c.example?`<div class="example">${esc(oneExample(c.example))}</div>`:''}`};const flash=document.getElementById('flash');flash.classList.remove('flipped');flash.onclick=()=>flash.classList.toggle('flipped');if(reviewMode==='srs'){rate.innerHTML=`<button class="btn again" data-rate="again">Again</button><button class="btn hard" data-rate="hard">Hard</button><button class="btn good" data-rate="good">Good</button><button class="btn easy" data-rate="easy">Easy</button>`;rate.querySelectorAll('[data-rate]').forEach(btn=>btn.onclick=()=>rateCard(btn.dataset.rate));nav.innerHTML=''}else{rate.innerHTML='';nav.innerHTML=`<button class="btn ghost" id="prevCard">← Previous</button><button class="btn ghost" id="nextCard">Next →</button>`;document.getElementById('prevCard').onclick=()=>{reviewIndex=(reviewIndex-1+reviewQueue.length)%reviewQueue.length;renderCard()};document.getElementById('nextCard').onclick=()=>{reviewIndex=(reviewIndex+1)%reviewQueue.length;renderCard()}}}
function rateCard(kind){const c=reviewQueue[reviewIndex],p=progressFor(c.id);if(kind==='again'){p.reps=0;p.interval=0;p.due=today()}if(kind==='hard'){p.reps++;p.interval=Math.max(1,Math.round((p.interval||1)*1.2));p.ease=Math.max(1.3,p.ease-.15);p.due=addDays(p.interval)}if(kind==='good'){p.reps++;p.interval=p.reps===1?1:p.reps===2?3:Math.max(3,Math.round(p.interval*p.ease));p.due=addDays(p.interval)}if(kind==='easy'){p.reps++;p.ease+=.15;p.interval=p.reps===1?4:Math.max(5,Math.round((p.interval||2)*p.ease*1.25));p.due=addDays(p.interval)}local.progress[c.id]=p;writeJSON(KEYS.local,local);reviewQueue.splice(reviewIndex,1);if(reviewIndex>=reviewQueue.length)reviewIndex=0;renderCard()}

function renderQuizShell(){const el=document.getElementById('view-quiz');el.innerHTML=`<div class="chip-row" style="margin-bottom:12px">${[['mixed','Mixed'],['vocab','Vocabulary'],['grammar','Grammar']].map(([k,n])=>`<button class="chip ${quizType===k?'active':''}" data-qtype="${k}">${n}</button>`).join('')}</div><div class="quiz-card" id="quizCard"></div>`;document.querySelectorAll('[data-qtype]').forEach(b=>b.onclick=()=>{quizType=b.dataset.qtype;quiz=null;renderQuizShell()});newQuiz()}
function quizPool(){const p=currentPool();let arr=[];if(quizType!=='grammar')arr.push(...p.vocab.map(x=>({...x,_type:'v'})));if(quizType!=='vocab')arr.push(...p.grammar.map(x=>({...x,_type:'g'})));return arr}
function newQuiz(){const pool=quizPool(),box=document.getElementById('quizCard');if(!box)return;if(pool.length<2){box.innerHTML='<div class="empty">Not enough items for this quiz type yet.</div>';return}const target=pool[Math.floor(Math.random()*pool.length)];let question,correct,others;if(target._type==='v'){const reverse=Math.random()<.5;question=reverse?target.meaning:target.korean;correct=reverse?target.korean:target.meaning;others=pool.filter(x=>x._type==='v'&&x.id!==target.id).map(x=>reverse?x.korean:x.meaning).filter(Boolean)}else{question=target.pattern;correct=target.explain;others=pool.filter(x=>x._type==='g'&&x.id!==target.id).map(x=>x.explain).filter(Boolean)}others=[...new Set(others)].sort(()=>Math.random()-.5).slice(0,3);quiz={target,question,correct,choices:[correct,...others].sort(()=>Math.random()-.5),answered:false};box.innerHTML=`<div class="muted">${target._type==='v'?'Vocabulary':'Grammar'}</div><h3 style="margin:7px 0 0">${esc(question)}</h3><div class="quiz-options">${quiz.choices.map((c,i)=>`<button class="quiz-choice" data-i="${i}">${esc(c.length>180?c.slice(0,180)+'…':c)}</button>`).join('')}</div><div class="quiz-feedback" id="quizFeedback"></div>`;box.querySelectorAll('.quiz-choice').forEach((b,i)=>b.onclick=()=>answerQuiz(i))}
function answerQuiz(i){if(quiz.answered)return;quiz.answered=true;document.querySelectorAll('.quiz-choice').forEach((b,j)=>{if(quiz.choices[j]===quiz.correct)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});document.getElementById('quizFeedback').innerHTML=`${quiz.choices[i]===quiz.correct?'<b>Correct.</b>':'<b>Not quite.</b>'}<div style="margin-top:6px">${esc(quiz.correct)}</div>${quiz.target.example?`<div class="entry-example" style="margin-top:8px">${esc(oneExample(quiz.target.example))}</div>`:''}<button class="btn primary" style="margin-top:12px" id="nextQuiz">Next question</button>`;document.getElementById('nextQuiz').onclick=newQuiz}

function openModal(html){document.getElementById('modal').innerHTML=html;document.getElementById('modalBg').classList.add('open');document.getElementById('modalBg').setAttribute('aria-hidden','false')}
function closeModal(){document.getElementById('modalBg').classList.remove('open');document.getElementById('modalBg').setAttribute('aria-hidden','true')}
document.getElementById('modalBg').onclick=e=>{if(e.target.id==='modalBg')closeModal()}
function modalActions(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}

function openVocab(id=null){const v=id?local.vocab.find(x=>x.id===id):null;openModal(`<h2>${v?'Edit':'Add'} vocabulary</h2><label>Lesson</label><select id="mLesson">${allLessons.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')}</select><label>Korean</label><input id="mKorean" value="${esc(v?.korean||'')}"><div class="two-col"><div><label>Part of speech</label><input id="mPos" value="${esc(v?.pos||'')}"></div><div><label>Meaning</label><input id="mMeaning" value="${esc(v?.meaning||'')}"></div></div><label>Word origin / mnemonic</label><input id="mOrigin" value="${esc(v?.origin||'')}" placeholder="e.g. 漢字: 學校 / English loanword"><label>Example sentences — one per line</label><textarea id="mExample">${esc(v?.example||'')}</textarea><label>Image URL (optional)</label><input id="mImage" value="${esc(v?.image||'')}"><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="mSave">Save</button></div>`);modalActions();document.getElementById('mLesson').value=v?.lessonId||(currentLesson!=='all'?currentLesson:allLessons[0]?.id||'');document.getElementById('mSave').onclick=()=>{const korean=document.getElementById('mKorean').value.trim();if(!korean)return;const obj={id:v?.id||'pv-'+uid(),lessonId:document.getElementById('mLesson').value,korean,pos:document.getElementById('mPos').value.trim(),meaning:document.getElementById('mMeaning').value.trim(),origin:document.getElementById('mOrigin').value.trim(),example:document.getElementById('mExample').value.trim(),image:document.getElementById('mImage').value.trim(),shared:false};local.vocab=v?local.vocab.map(x=>x.id===v.id?obj:x):[...local.vocab,obj];writeJSON(KEYS.local,local);closeModal();merge();renderAll()}}
function openGrammar(id=null){const g=id?local.grammar.find(x=>x.id===id):null;openModal(`<h2>${g?'Edit':'Add'} grammar</h2><label>Lesson</label><select id="mLesson">${allLessons.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')}</select><label>Pattern</label><input id="mPattern" value="${esc(g?.pattern||'')}"><label>Explanation</label><textarea id="mExplain">${esc(g?.explain||'')}</textarea><label>Example sentences — one per line</label><textarea id="mExample">${esc(g?.example||'')}</textarea><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="mSave">Save</button></div>`);modalActions();document.getElementById('mLesson').value=g?.lessonId||(currentLesson!=='all'?currentLesson:allLessons[0]?.id||'');document.getElementById('mSave').onclick=()=>{const pattern=document.getElementById('mPattern').value.trim();if(!pattern)return;const obj={id:g?.id||'pg-'+uid(),lessonId:document.getElementById('mLesson').value,pattern,explain:document.getElementById('mExplain').value.trim(),example:document.getElementById('mExample').value.trim(),shared:false};local.grammar=g?local.grammar.map(x=>x.id===g.id?obj:x):[...local.grammar,obj];writeJSON(KEYS.local,local);closeModal();merge();renderAll()}}
window.editV=openVocab;window.editG=openGrammar;window.toggleFav=toggleFav;window.switchView=switchView;

function openImport(){openModal(`<h2>Import & backup</h2><p class="import-note"><b>Best workflow for textbook / PPT:</b> upload the material to ChatGPT, ask for a “Korean Review lesson pack”, then import the JSON here. That keeps the public site free of API keys and gives you a review step before anything is published.</p><div class="dropzone"><b>Import a JSON lesson pack</b><p class="import-note">This adds the pack to your personal browser data. For content everyone should see, I can also add the reviewed pack directly to <code>shared-content.json</code> in GitHub.</p><input type="file" id="packFile" accept="application/json"></div><h3>Personal backup</h3><div class="two-col"><button class="btn ghost" id="exportPersonal">Export my notes & progress</button><label class="btn ghost" style="text-align:center;cursor:pointer">Restore personal backup<input type="file" id="restorePersonal" accept="application/json" hidden></label></div><h3>Lesson-pack format</h3><div class="code-hint">{"lessons":[{"name":"Lesson 10"}],"vocab":[{"lesson":"Lesson 10","korean":"학교","meaning":"school","origin":"學校","example":"학교에 가요."}],"grammar":[{"lesson":"Lesson 10","pattern":"-고 싶다","explain":"want to…","example":"한국에 가고 싶어요."}]}</div><div class="modal-actions"><button class="btn ghost" data-close>Close</button></div>`);modalActions();document.getElementById('packFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{importPack(JSON.parse(r.result));alert('Lesson pack imported.');closeModal()}catch(err){alert('Could not import this JSON file.')}};r.readAsText(f)};document.getElementById('exportPersonal').onclick=()=>{const blob=new Blob([JSON.stringify(local,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='korean-review-personal-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};document.getElementById('restorePersonal').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d||!Array.isArray(d.vocab)||!Array.isArray(d.grammar))throw new Error('bad');local=d;if(!Array.isArray(local.favorites))local.favorites=[];writeJSON(KEYS.local,local);merge();renderAll();alert('Personal backup restored.');closeModal()}catch{alert('This is not a valid personal backup.')}};r.readAsText(f)}}
function importPack(data){const incomingLessons=(data.lessons||[]).map(l=>typeof l==='string'?{name:l}:l).filter(l=>l.name).map(l=>({id:'p-'+uid(),name:l.name,shared:false}));const nameToId=new Map(incomingLessons.map(l=>[l.name,l.id]));const getId=name=>{const existing=allLessons.find(l=>l.name===name);return existing?.id||nameToId.get(name)||'p-'+uid()};incomingLessons.forEach(l=>{if(!local.lessons.some(x=>x.name===l.name))local.lessons.push(l)});(data.vocab||[]).forEach(v=>{if(!v.korean)return;local.vocab.push({id:'pv-'+uid(),lessonId:getId(v.lesson||v.lessonName||'Imported'),korean:v.korean,pos:v.pos||'',meaning:v.meaning||'',origin:v.origin||'',example:Array.isArray(v.example)?v.example.join('\n'):(v.example||''),image:v.image||'',shared:false})});(data.grammar||[]).forEach(g=>{if(!g.pattern)return;local.grammar.push({id:'pg-'+uid(),lessonId:getId(g.lesson||g.lessonName||'Imported'),pattern:g.pattern,explain:g.explain||g.explanation||'',example:Array.isArray(g.example)?g.example.join('\n'):(g.example||''),shared:false})});writeJSON(KEYS.local,local);merge();renderAll()}

function openAppearance(){openModal(`<h2>Appearance</h2><p class="import-note">Choose a preset or make your own. The choice stays on this device.</p><div class="theme-presets">${Object.entries(THEMES).map(([k,t])=>`<button class="theme-swatch ${themeState.preset===k&&!themeState.custom?'active':''}" data-theme="${k}" style="background:linear-gradient(135deg,${t.bg} 0 50%,${t.accent} 50% 100%)" title="${t.name}"></button>`).join('')}</div><h3>Custom colors</h3><div class="two-col"><label>Background<input type="color" id="customBg" value="${(themeState.custom||THEMES[themeState.preset]||THEMES.celadon).bg}"></label><label>Accent<input type="color" id="customAccent" value="${(themeState.custom||THEMES[themeState.preset]||THEMES.celadon).accent}"></label></div><div class="modal-actions"><button class="btn ghost" id="resetTheme">Reset</button><button class="btn ghost" data-close>Close</button><button class="btn primary" id="saveCustomTheme">Use custom</button></div>`);modalActions();document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{themeState={preset:b.dataset.theme,custom:null};writeJSON(KEYS.theme,themeState);applyTheme();openAppearance()});document.getElementById('saveCustomTheme').onclick=()=>{const base=THEMES[themeState.preset]||THEMES.celadon;themeState={preset:themeState.preset,custom:{...base,bg:document.getElementById('customBg').value,accent:document.getElementById('customAccent').value,accent2:document.getElementById('customAccent').value}};writeJSON(KEYS.theme,themeState);applyTheme();closeModal()};document.getElementById('resetTheme').onclick=()=>{themeState={preset:'celadon',custom:null};writeJSON(KEYS.theme,themeState);applyTheme();openAppearance()}}
function openAdvanced(){openModal(`<h2>Advanced settings</h2><p class="import-note">Most users never need this. These links are only for the shared Google Sheet source.</p><label>Lessons CSV</label><input id="cfgLessons" value="${esc(config.lessons||'')}"><label>Vocabulary CSV</label><input id="cfgVocab" value="${esc(config.vocab||'')}"><label>Grammar CSV</label><input id="cfgGrammar" value="${esc(config.grammar||'')}"><div class="code-hint" style="margin-top:12px">Loaded from Sheets: ${loadStats.lessons} lessons · ${loadStats.vocab} vocabulary · ${loadStats.grammar} grammar${loadStats.errors.length?`\nErrors: ${loadStats.errors.join(' | ')}`:''}</div><div class="modal-actions"><button class="btn ghost" id="resetConfig">Use defaults</button><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="saveConfig">Save & reload</button></div>`);modalActions();document.getElementById('resetConfig').onclick=()=>{config={...DEFAULT_CONFIG};writeJSON(KEYS.config,config);closeModal();loadShared()};document.getElementById('saveConfig').onclick=()=>{config={lessons:normalizeCsvUrl(document.getElementById('cfgLessons').value),vocab:normalizeCsvUrl(document.getElementById('cfgVocab').value),grammar:normalizeCsvUrl(document.getElementById('cfgGrammar').value)};writeJSON(KEYS.config,config);closeModal();loadShared()}}
function openSearch(){openModal(`<h2>Search everything</h2><div class="search-overlay"><input id="globalSearch" autofocus placeholder="Korean, meaning, origin, grammar…"></div><div class="search-results" id="searchResults"></div><div class="modal-actions"><button class="btn ghost" data-close>Close</button></div>`);modalActions();const input=document.getElementById('globalSearch'),results=document.getElementById('searchResults');input.oninput=()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='<div class="empty">Start typing to search.</div>';return}const matches=[...allVocab.map(x=>({...x,_type:'v'})),...allGrammar.map(x=>({...x,_type:'g'}))].filter(x=>JSON.stringify(x).toLowerCase().includes(q)).slice(0,30);results.innerHTML=matches.length?matches.map(x=>`<div class="search-result" data-id="${x.id}" data-lesson="${x.lessonId}"><b>${esc(x._type==='v'?x.korean:x.pattern)}</b><div class="muted">${esc(x._type==='v'?x.meaning:x.explain)}</div></div>`).join(''):'<div class="empty">No matches.</div>';results.querySelectorAll('.search-result').forEach(r=>r.onclick=()=>{currentLesson=r.dataset.lesson;browseQuery=input.value;closeModal();switchView('browse')})};input.dispatchEvent(new Event('input'));setTimeout(()=>input.focus(),0)}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';window.speechSynthesis.speak(u)}
function openDict(q){window.open('https://en.dict.naver.com/#/search?query='+encodeURIComponent(q),'_blank','noopener')}
window.speak=speak;window.openDict=openDict;

document.getElementById('addLessonBtn').onclick=()=>{openModal(`<h2>Add personal lesson</h2><label>Lesson name</label><input id="newLesson"><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="saveLesson">Save</button></div>`);modalActions();document.getElementById('saveLesson').onclick=()=>{const name=document.getElementById('newLesson').value.trim();if(!name)return;local.lessons.push({id:'p-'+uid(),name,shared:false});writeJSON(KEYS.local,local);closeModal();merge();renderAll()}};
document.getElementById('importBtn').onclick=openImport;document.getElementById('appearanceBtn').onclick=openAppearance;document.getElementById('settingsBtn').onclick=openAdvanced;document.getElementById('globalSearchBtn').onclick=openSearch;

loadShared();