const DEFAULT_CONFIG={
  lessons:'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_LKSMUYj7ehGgazL1-sujxiznaWetrYLHPGTRJ9UEHJxYf7r9rNeU5I6Gqenm6e3gQafDA_sZKbKC/pub?gid=0&single=true&output=csv',
  vocab:'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_LKSMUYj7ehGgazL1-sujxiznaWetrYLHPGTRJ9UEHJxYf7r9rNeU5I6Gqenm6e3gQafDA_sZKbKC/pub?gid=754782420&single=true&output=csv',
  grammar:'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_LKSMUYj7ehGgazL1-sujxiznaWetrYLHPGTRJ9UEHJxYf7r9rNeU5I6Gqenm6e3gQafDA_sZKbKC/pub?gid=1482161321&single=true&output=csv'
};
const KEYS={local:'koreanReviewLocal_v4',config:'koreanReviewConfig_v4',theme:'koreanReviewTheme_v1'};
const THEMES={
  celadon:{name:'Celadon',bg:'#edf3ee',panel:'#ffffff',ink:'#1b2b22',accent:'#365446',accent2:'#4c7a66',soft:'#e7efe9',warm:'#c9683c',gold:'#d89a3a',line:'#ccd8cf'},
  ink:{name:'Ink',bg:'#f2f2f0',panel:'#ffffff',ink:'#1e2525',accent:'#253f46',accent2:'#4e6b73',soft:'#e8edef',warm:'#9f5b42',gold:'#b48c39',line:'#d4d8d7'},
  peach:{name:'Peach',bg:'#fbf1e9',panel:'#fffdfb',ink:'#352721',accent:'#7d4e43',accent2:'#9a6b5d',soft:'#f5e3d7',warm:'#c56c4f',gold:'#c79a45',line:'#ead6c8'},
  lilac:{name:'Lilac',bg:'#f2eff8',panel:'#ffffff',ink:'#2f2938',accent:'#554769',accent2:'#75658a',soft:'#ebe5f2',warm:'#a75f72',gold:'#b08b43',line:'#dad2e3'}
};
const BASICS=[
  {title:'Hangul syllable blocks',short:'Korean letters combine into square syllable blocks.',body:'A common block has an initial consonant (초성) + vowel (중성), with an optional final consonant (종성 / 받침).',formula:'초성 + 중성 (+ 종성) → 한 글자'},
  {title:'Basic sentence order',short:'A common default is Subject – Object – Verb.',body:'Korean tends to put the predicate at the end. Particles help show each noun’s role, so word order can be more flexible than English.',formula:'저는 + 한국어를 + 공부해요.'},
  {title:'Core particles',short:'은/는, 이/가, 을/를 help organize information.',body:'은/는 often marks a topic or contrast; 이/가 marks the grammatical subject or focus; 을/를 marks the object. Context matters more than one-to-one English translations.',formula:'저는 학생이에요. / 비가 와요. / 책을 읽어요.'},
  {title:'Politeness endings',short:'Sentence endings carry social meaning.',body:'Begin with 해요체 (-아요/어요) for everyday polite speech, then learn 합니다체 (-ㅂ니다/습니다) for more formal situations.',formula:'가요 / 먹어요 / 갑니다 / 먹습니다'},
  {title:'Two number systems',short:'Native Korean and Sino-Korean numbers have different jobs.',body:'Hours and many counters often use Native Korean numbers; dates, money, phone numbers, minutes, and many measurements often use Sino-Korean numbers.',formula:'한 시 / 일 분'}
];

function readJSON(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
function writeJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function today(){return new Date().toISOString().slice(0,10)}
function addDays(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function lessonKey(s){s=String(s||'').trim();const m=s.match(/(?:lesson\s*)?(\d+)/i);if(m)return 'lesson-'+m[1];return s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9가-힣]+/g,'-').replace(/^-|-$/g,'')||'unsorted'}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function normalizeAnswer(s){return String(s||'').trim().toLowerCase().replace(/[.,!?]/g,'').replace(/\s+/g,' ')}
function oneExample(s){const a=String(s||'').split(/\r?\n|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);return a.length?a[Math.floor(Math.random()*a.length)]:''}

let local=readJSON(KEYS.local,{});
local={lessons:[],vocab:[],grammar:[],progress:{},favorites:[],mistakes:[],attempts:{},activity:[],feedback:[],...local};
if(!Array.isArray(local.favorites))local.favorites=[];if(!Array.isArray(local.mistakes))local.mistakes=[];if(!local.attempts)local.attempts={};if(!Array.isArray(local.activity))local.activity=[];if(!Array.isArray(local.feedback))local.feedback=[];
let config=readJSON(KEYS.config,DEFAULT_CONFIG);let themeState=readJSON(KEYS.theme,{preset:'celadon',custom:null});
let shared={lessons:[],vocab:[],grammar:[]},repoPack={lessons:[],vocab:[],grammar:[]},coursePack=null,coursePacks=[],lessonPackIndex=null,verificationRegister=null,conceptRegistry=null,systemMap=null,conceptCrosswalk=null,verificationKeys=new Set();
let allLessons=[],allVocab=[],allGrammar=[];let currentLesson='lesson-13',currentView='today',browseType='all',browseQuery='',reviewMode='srs',reviewQueue=[],reviewIndex=0;
let practiceFilter='smart',practiceQueue=[],practiceIndex=0,practiceAnswered=false;let quizFilter='all',quizQueue=[],quizIndex=0,quizScore=0,quizAnswered=false;
let loadStats={sheet:0,repo:0,course:0,errors:[]};

function applyTheme(){let t=themeState.custom||THEMES[themeState.preset]||THEMES.celadon;const r=document.documentElement;[['--bg','bg'],['--panel','panel'],['--ink','ink'],['--accent','accent'],['--accent-2','accent2'],['--accent-soft','soft'],['--warm','warm'],['--gold','gold'],['--line','line']].forEach(([css,k])=>r.style.setProperty(css,t[k]||THEMES.celadon[k]))}
applyTheme();

const headerAlias={lesson:'lesson','lesson name':'lesson',name:'name',korean:'korean','korean word':'korean',word:'korean',term:'korean',pos:'pos','part of speech':'pos',meaning:'meaning','english meaning':'meaning',definition:'meaning',origin:'origin','word origin':'origin',etymology:'origin',example:'example','example sentence':'example',examples:'example',image:'image','image url':'image',pattern:'pattern','grammar pattern':'pattern',grammar:'pattern',explain:'explain',explanation:'explain','grammar explanation':'explain'};
function cleanHeader(h){h=String(h||'').replace(/^\ufeff/,'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');return headerAlias[h]||h}
function normalizeCsvUrl(url){url=String(url||'').trim();if(!url)return '';try{if(url.includes('/pubhtml'))url=url.replace('/pubhtml','/pub');if(url.includes('/pub?')){const u=new URL(url);u.searchParams.set('single','true');u.searchParams.set('output','csv');return u.toString()}}catch{}return url}
async function fetchCsv(url,label){const res=await fetch(normalizeCsvUrl(url),{cache:'no-store'});if(!res.ok)throw new Error(`${label}: HTTP ${res.status}`);const text=await res.text();const parsed=Papa.parse(text,{header:true,skipEmptyLines:'greedy',transformHeader:cleanHeader});return parsed.data.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[cleanHeader(k),String(v??'').trim()]))) }
async function fetchJson(path){const r=await fetch(`${path}?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json()}

async function loadContent(){
  document.getElementById('syncStatus').textContent='Loading course content…';loadStats={sheet:0,repo:0,course:0,errors:[]};
  const [courseRes,repoRes,lessonIndexRes,verificationRes,conceptRes,systemRes,crosswalkRes]=await Promise.allSettled([fetchJson('content/lesson13.json'),fetchJson('shared-content.json'),fetchJson('content/lessons-v1/index.json'),fetchJson('content/enrichment-verification-v1.json'),fetchJson('content/concept-registry-v1.json'),fetchJson('content/system-map-v1.json'),fetchJson('content/concept-crosswalk-v1.json')]);
  coursePack=courseRes.status==='fulfilled'?courseRes.value:null;if(!coursePack)loadStats.errors.push('Lesson 13 pack failed to load');
  repoPack=repoRes.status==='fulfilled'?repoRes.value:{lessons:[],vocab:[],grammar:[]};
  lessonPackIndex=lessonIndexRes.status==='fulfilled'?lessonIndexRes.value:null;if(!lessonPackIndex)loadStats.errors.push('Lesson 1-14 index failed to load');
  verificationRegister=verificationRes.status==='fulfilled'?verificationRes.value:null;if(!verificationRegister)loadStats.errors.push('Enrichment verification register failed to load');
  conceptRegistry=conceptRes.status==='fulfilled'?conceptRes.value:null;
  systemMap=systemRes.status==='fulfilled'?systemRes.value:null;
  conceptCrosswalk=crosswalkRes.status==='fulfilled'?crosswalkRes.value:null;
  verificationKeys=new Set((verificationRegister?.verifiedItems||[]).map(item=>`${item.lessonId}::${item.itemId}`));
  const lessonPackFiles=(lessonPackIndex?.packs||[]).map(p=>`content/lessons-v1/${p.file}`);
  if(lessonPackFiles.length){
    const packResults=await Promise.allSettled(lessonPackFiles.map(file=>fetchJson(file)));
    coursePacks=packResults.filter(r=>r.status==='fulfilled').map(r=>r.value);
    const failed=packResults.filter(r=>r.status==='rejected').length;if(failed)loadStats.errors.push(`${failed} structured lesson pack${failed===1?'':'s'} failed to load`);
  }else coursePacks=[];
  const urls={lessons:config.lessons||config.lessonsUrl||DEFAULT_CONFIG.lessons,vocab:config.vocab||config.vocabUrl||DEFAULT_CONFIG.vocab,grammar:config.grammar||config.grammarUrl||DEFAULT_CONFIG.grammar};config=urls;writeJSON(KEYS.config,config);
  const res=await Promise.allSettled([fetchCsv(urls.lessons,'Lessons'),fetchCsv(urls.vocab,'Vocabulary'),fetchCsv(urls.grammar,'Grammar')]);
  const L=res[0].status==='fulfilled'?res[0].value:(loadStats.errors.push(res[0].reason.message),[]);const V=res[1].status==='fulfilled'?res[1].value:(loadStats.errors.push(res[1].reason.message),[]);const G=res[2].status==='fulfilled'?res[2].value:(loadStats.errors.push(res[2].reason.message),[]);
  shared.lessons=L.filter(r=>r.name||r.lesson).map(r=>{const name=r.name||r.lesson;return{id:lessonKey(name),name,shared:true,source:'sheet'}});
  shared.vocab=V.filter(r=>r.korean).map(r=>({id:'sv-'+lessonKey(r.lesson)+'-'+lessonKey(r.korean),lessonId:lessonKey(r.lesson),lessonName:r.lesson||'Unsorted',korean:r.korean,pos:r.pos||'',meaning:r.meaning||'',origin:r.origin||'',example:r.example||'',image:r.image||'',shared:true,source:'sheet'}));
  shared.grammar=G.filter(r=>r.pattern).map(r=>({id:'sg-'+lessonKey(r.lesson)+'-'+lessonKey(r.pattern),lessonId:lessonKey(r.lesson),lessonName:r.lesson||'Unsorted',pattern:r.pattern,explain:r.explain||'',example:r.example||'',shared:true,source:'sheet'}));
  loadStats.sheet=shared.vocab.length+shared.grammar.length;loadStats.repo=(repoPack.vocab||[]).length+(repoPack.grammar||[]).length;loadStats.course=coursePack?(coursePack.vocabulary.length+coursePack.grammar.length):0;loadStats.lessonPacks=coursePacks.length;loadStats.verified=(verificationRegister?.verifiedItems||[]).length;
  merge();if(!allLessons.some(l=>l.id===currentLesson))currentLesson=allLessons[0]?.id||'all';renderAll();
}
function normalizeRepo(){const lessons=(repoPack.lessons||[]).map(l=>typeof l==='string'?{name:l}:l).filter(l=>l.name).map(l=>({id:l.id||lessonKey(l.name),name:l.name,shared:true,source:'repo'}));const vocab=(repoPack.vocab||[]).filter(v=>v.korean).map(v=>({id:v.id||'rv-'+lessonKey(v.lesson||v.lessonName)+'-'+lessonKey(v.korean),lessonId:v.lessonId||lessonKey(v.lesson||v.lessonName),lessonName:v.lesson||v.lessonName||'Unsorted',korean:v.korean,pos:v.pos||'',meaning:v.meaning||'',origin:v.origin||'',example:Array.isArray(v.example)?v.example.join('\n'):(v.example||''),image:v.image||'',shared:true,source:'repo'}));const grammar=(repoPack.grammar||[]).filter(g=>g.pattern).map(g=>({id:g.id||'rg-'+lessonKey(g.lesson||g.lessonName)+'-'+lessonKey(g.pattern),lessonId:g.lessonId||lessonKey(g.lesson||g.lessonName),lessonName:g.lesson||g.lessonName||'Unsorted',pattern:g.pattern,explain:g.explain||g.explanation||'',example:Array.isArray(g.example)?g.example.join('\n'):(g.example||''),shared:true,source:'repo'}));return{lessons,vocab,grammar}}
function normalizeCourse(){if(!coursePack)return{lessons:[],vocab:[],grammar:[]};const l=coursePack.lesson;return{lessons:[{id:l.id,name:l.name,shared:true,source:'course'}],vocab:coursePack.vocabulary.map(v=>({id:'cv-'+lessonKey(v.korean),lessonId:l.id,lessonName:l.name,korean:v.korean,meaning:v.meaning,pos:v.group||'',origin:'',example:'',group:v.group||'',shared:true,source:'course'})),grammar:coursePack.grammar.map(g=>({id:g.id,lessonId:l.id,lessonName:l.name,pattern:g.pattern,explain:g.explain,example:(g.examples||[]).join('\n'),code:g.code,title:g.title,formula:g.formula,contrast:g.contrast,pitfall:g.pitfall,shared:true,source:'course'}))}}
function lessonPackName(pack){const l=pack.lesson||{};return `Lesson ${l.number||String(l.id||'').replace(/\D/g,'')}: ${l.titleKo||l.name||'Untitled'}${l.titleEn?` · ${l.titleEn}`:''}`}
function packForLesson(id){return coursePacks.find(pack=>pack.lesson?.id===id)}
function verifiedItem(lessonId,itemId){return verificationKeys.has(`${lessonId}::${itemId}`)}
function formatExample(ex){if(!ex)return'';if(typeof ex==='string')return ex;return [ex.ko,ex.en].filter(Boolean).join(' — ')}
function normalizeLessonPacks(){const lessons=[],vocab=[],grammar=[];coursePacks.forEach(pack=>{const l=pack.lesson||{},lessonId=l.id||lessonKey(l.titleEn||l.titleKo||'lesson'),lessonName=lessonPackName(pack);lessons.push({id:lessonId,name:lessonName,shared:true,source:'lessons-v1',number:l.number||999});(pack.vocabulary||[]).forEach(v=>vocab.push({id:v.id||`lv-${lessonId}-${lessonKey(v.korean)}`,lessonId,lessonName,korean:v.korean,meaning:v.meaningEn||v.meaning||'',meaningZh:v.meaningZh||'',pos:v.pos||'',origin:[v.hanja,v.originType].filter(Boolean).join(' · '),hanja:v.hanja||'',originType:v.originType||'',originNote:v.originNote||'',example:'',tags:v.tags||[],verified:verifiedItem(lessonId,v.id),shared:true,source:'lessons-v1'}));(pack.grammar||[]).forEach(g=>grammar.push({id:g.id||`lg-${lessonId}-${lessonKey(g.pattern)}`,lessonId,lessonName,pattern:g.pattern,name:g.name||'',title:g.name||g.title||'',explain:g.meaning||g.explain||'',example:(g.examples||[]).map(formatExample).filter(Boolean).join('\n'),examples:(g.examples||[]).map(formatExample).filter(Boolean),formula:(g.formation||[]).join('\n'),contrast:(g.contrast||[]).map(c=>`${c.with}: ${c.note}`).join('\n'),pitfall:(g.commonMistakes||[]).join('\n'),tags:g.tags||[],shared:true,source:'lessons-v1'}))});return{lessons,vocab,grammar}}
function merge(){const rp=normalizeRepo(),cp=normalizeCourse(),lp=normalizeLessonPacks();const lessonMap=new Map();[...rp.lessons,...shared.lessons,...cp.lessons,...lp.lessons,...local.lessons].forEach(l=>lessonMap.set(l.id,l));const dedupe=(arr,keyFn)=>{const m=new Map();arr.forEach(x=>m.set(keyFn(x),x));return [...m.values()]};allVocab=dedupe([...shared.vocab,...rp.vocab,...cp.vocab,...lp.vocab,...local.vocab],v=>`${v.lessonId}::${v.korean}`);allGrammar=dedupe([...shared.grammar,...rp.grammar,...cp.grammar,...lp.grammar,...local.grammar],g=>`${g.lessonId}::${g.pattern}`);[...allVocab,...allGrammar].forEach(x=>{if(!lessonMap.has(x.lessonId))lessonMap.set(x.lessonId,{id:x.lessonId,name:x.lessonName||'Unsorted',shared:true})});allLessons=[...lessonMap.values()].sort((a,b)=>{const na=a.number||+(a.name.match(/\d+/)||[999])[0],nb=b.number||+(b.name.match(/\d+/)||[999])[0];return na-nb||a.name.localeCompare(b.name)})}

function currentPool(){return{vocab:allVocab.filter(v=>currentLesson==='all'||v.lessonId===currentLesson),grammar:allGrammar.filter(g=>currentLesson==='all'||g.lessonId===currentLesson)}}
function isFav(id){return local.favorites.includes(id)}
function toggleFav(id){local.favorites=isFav(id)?local.favorites.filter(x=>x!==id):[...local.favorites,id];writeJSON(KEYS.local,local);renderCurrent()}
function progressFor(id){return local.progress[id]||{reps:0,interval:0,ease:2.5,due:today()}}
function isDue(id){return progressFor(id).due<=today()}
function logActivity(kind){local.activity.push({date:today(),kind,ts:Date.now()});local.activity=local.activity.slice(-300);writeJSON(KEYS.local,local);renderStreak()}
function renderStreak(){const days=[...new Set(local.activity.map(x=>x.date))].sort().reverse();let streak=0,d=new Date();for(let i=0;i<60;i++){const s=d.toISOString().slice(0,10);if(days.includes(s)){streak++;d.setDate(d.getDate()-1)}else if(i===0){d.setDate(d.getDate()-1)}else break}document.getElementById('streakBadge').textContent=`${streak} day${streak===1?'':'s'} streak`}

function renderAll(){renderSync();renderLessons();renderStreak();renderCurrent()}
function renderSync(){const total=allVocab.length+allGrammar.length;document.getElementById('syncStatus').innerHTML=`<b>${total}</b> learning items<br>${loadStats.lessonPacks||0} structured lessons · ${loadStats.verified||0} verified QA${loadStats.sheet?` · ${loadStats.sheet} Sheets`:''}`;document.getElementById('banner').innerHTML=loadStats.errors.length?`<div class="banner">Some optional content sources did not load, but the site is still usable. ${esc(loadStats.errors.join(' · '))}</div>`:''}
function lessonCount(id){return allVocab.filter(v=>v.lessonId===id).length+allGrammar.filter(g=>g.lessonId===id).length}
function renderLessons(){const nav=document.getElementById('lessonList');nav.innerHTML='';const make=(id,name,count)=>{const b=document.createElement('button');b.className='lesson-link'+(currentLesson===id?' active':'');b.innerHTML=`<span>${esc(name)}</span><span class="lesson-count">${count}</span>`;b.onclick=()=>{currentLesson=id;practiceFilter='smart';quizFilter='all';renderAll()};nav.appendChild(b)};make('all','All lessons',allVocab.length+allGrammar.length);allLessons.forEach(l=>make(l.id,l.name,lessonCount(l.id)))}

const viewTitles={today:['Today','A small plan for your next Korean study session.'],lesson:['Lesson','See the structure of the lesson before drilling details.'],browse:['Browse','Search, compare, save, and hear what matters.'],practice:['Practice','Recall first, then use feedback to fix the reason you missed it.'],review:['Flashcards','Review with progressively longer intervals.'],quiz:['Quiz','A short mixed check of what you can retrieve.'],mistakes:['Mistakes','Turn errors into a targeted review list.'],basics:['Beginner','Build the foundations before memorizing details.'],qa:['Content QA','Teacher-source lesson packs and verified enrichment are separated here.'],explore:['Explore','Cross-lesson Korean systems and concept maps.']};
function switchView(view){currentView=view;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));const title=viewTitles[view]||viewTitles.today;document.getElementById('pageTitle').textContent=title[0];document.getElementById('pageSubtitle').textContent=title[1];renderCurrent()}
function renderCurrent(){if(currentView==='today')renderToday();if(currentView==='lesson')renderLesson();if(currentView==='browse')renderBrowse();if(currentView==='practice')renderPractice();if(currentView==='review')renderReview();if(currentView==='quiz')renderQuiz();if(currentView==='mistakes')renderMistakes();if(currentView==='basics')renderBasics();if(currentView==='qa')renderQa()}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));

function mistakeCounts(){const m={};local.mistakes.forEach(x=>m[x.tag]=(m[x.tag]||0)+x.count);return m}
function tagName(t){return({'phone':'Phone flow','body':'Body & health','g13-1':'G13.1 favors','g13-2':'G13.2 obligation','g13-3':'G13.3 promise','g13-4':'G13.4 reasons','g13-5':'G13.5 intention'})[t]||t}
function renderToday(){const el=document.getElementById('view-today'),p=currentPool();const cards=[...p.vocab,...p.grammar],due=cards.filter(c=>isDue(c.id)).length,mastered=cards.filter(c=>progressFor(c.id).interval>=14).length,pct=cards.length?Math.round(mastered/cards.length*100):0;const mc=mistakeCounts(),weak=Object.entries(mc).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(1,...weak.map(x=>x[1]));const lessonName=currentLesson==='all'?'All lessons':(allLessons.find(l=>l.id===currentLesson)?.name||'Lesson');el.innerHTML=`
<div class="grid stats"><div class="stat-card"><div class="stat-value">${due}</div><div class="stat-label">cards due</div></div><div class="stat-card"><div class="stat-value">${loadStats.lessonPacks||0}</div><div class="stat-label">structured lesson packs</div></div><div class="stat-card"><div class="stat-value">${loadStats.verified||0}</div><div class="stat-label">verified enrichment items</div></div><div class="stat-card"><div class="stat-value">${pct}%</div><div class="stat-label">mastered in ${esc(lessonName)}</div></div></div>
<div class="section-title"><h2>Recommended next</h2></div><div class="quick-actions"><button class="quick-card" data-go="qa"><b>Open Content QA</b><span class="muted">See teacher source, verified enrichment, and unverified enrichment boundaries.</span></button><button class="quick-card" data-go="lesson"><b>Open lesson map</b><span class="muted">Browse the structured Lesson 1-14 packs.</span></button><button class="quick-card" data-go="browse"><b>Browse all course data</b><span class="muted">Search vocabulary, grammar, Hanja, and Chinese glosses.</span></button><button class="quick-card" data-go="review"><b>Review ${due||'due'} cards</b><span class="muted">Spaced repetition keeps the session small.</span></button></div>
<div class="section-title"><h2>Mastery</h2><span class="muted">${mastered} / ${cards.length} mature cards</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>
<div class="section-title"><h2>Weakness map</h2></div>${weak.length?`<div class="card" style="padding:14px"><div class="weakness-list">${weak.map(([t,n])=>`<div class="weak-row"><span>${esc(tagName(t))}</span><div class="weak-bar"><span style="width:${Math.round(n/max*100)}%"></span></div><b>${n}</b></div>`).join('')}</div></div>`:`<div class="empty">No mistakes yet. Once you practice, this section will point you toward the concepts that need attention.</div>`}`;el.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go))}

function renderLesson(){const el=document.getElementById('view-lesson'),structuredPack=packForLesson(currentLesson);if(structuredPack){renderStructuredLesson(el,structuredPack);return}if(currentLesson!=='lesson-13'||!coursePack){const p=currentPool();el.innerHTML=`<div class="lesson-hero"><div class="lesson-eyebrow">Lesson overview</div><h2>${esc(allLessons.find(l=>l.id===currentLesson)?.name||'All lessons')}</h2><div class="muted">${p.vocab.length} vocabulary · ${p.grammar.length} grammar points</div></div><div class="section-title"><h2>Grammar</h2></div><div class="lesson-layout">${p.grammar.map(grammarCardHtml).join('')||'<div class="empty">No detailed lesson map yet.</div>'}</div>`;bindLessonButtons();return}
 const l=coursePack.lesson;el.innerHTML=`<div class="lesson-hero"><div class="lesson-eyebrow">Class pack · integrated prototype</div><h2>${esc(l.name)} <span class="muted">${esc(l.english)}</span></h2><p class="muted" style="line-height:1.6">${esc(l.summary)}</p><div class="lesson-goals">${l.goals.map(g=>`<div class="goal">✓ ${esc(g)}</div>`).join('')}</div></div>
<div class="section-title"><h2>Class focus</h2><span class="muted">Distilled from the lesson materials you uploaded</span></div><div class="focus-row">${l.classFocus.map(x=>`<span class="focus-chip">${esc(x)}</span>`).join('')}</div>
<div class="section-title"><h2>Telephone flow</h2><button class="btn ghost small grow" id="practicePhone">Practice phone flow</button></div><div class="phone-flow">${coursePack.phoneFlow.map(s=>`<div class="flow-step"><div class="flow-num">${esc(s.step)}</div><b>${esc(s.label)}</b><div class="flow-kr">${esc(s.korean)}</div><p>${esc(s.hint)}</p></div>`).join('')}</div>
<div class="section-title"><h2>Body & health</h2><span class="muted">Tap a body part to build a symptom sentence.</span></div><div class="lesson-card"><div class="body-grid">${coursePack.vocabulary.filter(v=>v.group==='body').map(v=>`<button class="body-word" data-body="${esc(v.korean)}"><b>${esc(v.korean)}</b><small>${esc(v.meaning)}</small></button>`).join('')}</div><div class="body-result" id="bodyResult">어디가 아파요? → choose a body part</div></div>
<div class="section-title"><h2>Grammar map</h2></div><div class="lesson-layout">${coursePack.grammar.map(grammarCardHtml).join('')}</div>`;
 document.getElementById('practicePhone').onclick=()=>{practiceFilter='phone';resetPractice();switchView('practice')};el.querySelectorAll('[data-body]').forEach(b=>b.onclick=()=>{const noun=b.dataset.body,particle=/[가-힣]/.test(noun)&&hasBatchim(noun)?'이':'가';document.getElementById('bodyResult').innerHTML=`<b>${esc(noun+particle+' 아파요.')}</b> <span class="muted">— My ${esc(coursePack.vocabulary.find(v=>v.korean===noun)?.meaning||'body part')} hurts.</span>`});bindLessonButtons()}
function renderStructuredLesson(el,pack){const l=pack.lesson||{},p=currentPool(),qa=pack.sourcePolicy?.enrichmentQa||{},verifiedIds=new Set(qa.verifiedItemIds||[]),vocab=(pack.vocabulary||[]),grammar=(pack.grammar||[]),verifiedCount=vocab.filter(v=>verifiedIds.has(v.id)).length;el.innerHTML=`<div class="lesson-hero"><div class="lesson-eyebrow">Teacher PPT structured pack · ${esc(pack.sourcePolicy?.enrichmentQa?.status||'mixed QA')}</div><h2>Lesson ${esc(l.number||'')} · ${esc(l.titleKo||'')} <span class="muted">${esc(l.titleEn||'')}</span></h2><p class="muted" style="line-height:1.6">${esc(l.theme||'')}</p><div class="lesson-goals"><div class="goal"><b>${vocab.length}</b><br>vocabulary items</div><div class="goal"><b>${grammar.length}</b><br>grammar points</div><div class="goal"><b>${verifiedCount}</b><br>verified enrichment items</div><div class="goal"><b>${(pack.practice||[]).length}</b><br>practice prompts</div></div></div>
${l.teacherFocus?.length?`<div class="section-title"><h2>Teacher Focus</h2><span class="muted">Derived from the lesson PPT structure</span></div><div class="focus-row">${l.teacherFocus.map(x=>`<span class="focus-chip">${esc(x)}</span>`).join('')}</div>`:''}
${l.goals?.length?`<div class="section-title"><h2>Lesson Goals</h2></div><div class="lesson-goals">${l.goals.map(g=>`<div class="goal">${esc(g)}</div>`).join('')}</div>`:''}
<div class="section-title"><h2>Vocabulary Source QA</h2><span class="muted">${verifiedCount} verified · ${Math.max(0,vocab.length-verifiedCount)} still labeled enrichment</span></div><div class="qa-vocab-grid">${vocab.slice(0,18).map(v=>`<article class="qa-vocab-card"><div class="qa-vocab-top"><b>${esc(v.korean)}</b><span class="qa-badge ${verifiedIds.has(v.id)?'verified':'unverified'}">${verifiedIds.has(v.id)?'verified':'unverified'}</span></div><div class="muted">${esc(v.meaningEn||'')}${v.meaningZh?` · ${esc(v.meaningZh)}`:''}</div>${v.hanja?`<div class="entry-origin">${esc(v.hanja)} · ${esc(v.originType||'')}</div>`:''}</article>`).join('')}</div>${vocab.length>18?`<div class="muted" style="margin-top:8px">Showing 18 of ${vocab.length}; use Browse for the full lesson list.</div>`:''}
<div class="section-title"><h2>Grammar Map</h2><span class="muted">${p.grammar.length} items loaded into Browse and Flashcards</span></div><div class="lesson-layout">${p.grammar.map(grammarCardHtml).join('')||'<div class="empty">No grammar items loaded for this lesson.</div>'}</div>`;bindLessonButtons()}
function grammarCardHtml(g){const examples=(g.examples||String(g.example||'').split('\n').filter(Boolean));return `<article class="lesson-card"><span class="grammar-code">${esc(g.code||'Grammar')}</span><h3>${esc(g.pattern)} · ${esc(g.title||'')}</h3><p class="muted" style="line-height:1.55">${esc(g.explain)}</p>${g.formula?`<div class="formula">${esc(g.formula)}</div>`:''}${examples.length?`<div class="examples">${examples.slice(0,3).map(x=>`<div class="example-box">${esc(x)}</div>`).join('')}</div>`:''}${g.contrast?`<div class="compare-box"><b>Compare:</b> ${esc(g.contrast)}</div>`:''}${g.pitfall?`<div class="pitfall"><b>Watch out:</b> ${esc(g.pitfall)}</div>`:''}<button class="btn ghost small" style="margin-top:12px" data-practice-tag="${esc(g.id)}">Practice this</button></article>`}
function bindLessonButtons(){document.querySelectorAll('[data-practice-tag]').forEach(b=>b.onclick=()=>{practiceFilter=b.dataset.practiceTag;resetPractice();switchView('practice')})}
function hasBatchim(word){const c=word.charCodeAt(word.length-1);if(c<0xAC00||c>0xD7A3)return false;return (c-0xAC00)%28!==0}

function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';window.speechSynthesis.speak(u)}
function renderBrowse(){const el=document.getElementById('view-browse'),p=currentPool();let items=[...p.vocab.map(x=>({...x,_type:'v'})),...p.grammar.map(x=>({...x,_type:'g'}))];if(browseType==='vocab')items=items.filter(x=>x._type==='v');if(browseType==='grammar')items=items.filter(x=>x._type==='g');if(browseType==='saved')items=items.filter(x=>isFav(x.id));if(browseQuery){const q=browseQuery.toLowerCase();items=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q))}el.innerHTML=`<div class="browse-tools"><input id="browseSearch" placeholder="Search Korean, meaning, grammar, example…" value="${esc(browseQuery)}"><div class="chip-row">${[['all','All'],['vocab','Vocabulary'],['grammar','Grammar'],['saved','★ Saved']].map(([k,n])=>`<button class="chip ${browseType===k?'active':''}" data-btype="${k}">${n}</button>`).join('')}</div></div><div class="list">${items.length?items.map(entryHtml).join(''):'<div class="empty">No matching items.</div>'}</div>`;document.getElementById('browseSearch').oninput=e=>{browseQuery=e.target.value;renderBrowse()};el.querySelectorAll('[data-btype]').forEach(b=>b.onclick=()=>{browseType=b.dataset.btype;renderBrowse()});el.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));el.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak))}
function entryHtml(x){if(x._type==='v')return `<div class="entry"><div class="entry-body"><div><span class="entry-title">${esc(x.korean)}</span>${x.pos?`<span class="entry-meta">${esc(x.pos)}</span>`:''}${x.source==='lessons-v1'?` <span class="qa-badge ${x.verified?'verified':'unverified'}">${x.verified?'verified enrichment':'unverified enrichment'}</span>`:''} <button class="btn ghost small" data-speak="${esc(x.korean)}">🔊</button></div><div class="entry-meaning">${esc(x.meaning)}${x.meaningZh?` · ${esc(x.meaningZh)}`:''}</div>${x.origin?`<div class="entry-origin">${esc(x.origin)}</div>`:''}${x.originNote?`<div class="entry-example">${esc(x.originNote)}</div>`:''}${x.example?`<div class="entry-example">${esc(oneExample(x.example))}</div>`:''}</div><div class="entry-actions"><button class="star ${isFav(x.id)?'on':''}" data-fav="${esc(x.id)}">★</button></div></div>`;return `<div class="entry"><div class="entry-body"><div><span class="entry-title">${esc(x.pattern)}</span>${x.code?`<span class="entry-meta">${esc(x.code)}</span>`:''}</div><div class="entry-meaning">${esc(x.explain)}</div>${x.contrast?`<div class="compare-box"><b>Compare:</b> ${esc(x.contrast)}</div>`:''}</div><div class="entry-actions"><button class="star ${isFav(x.id)?'on':''}" data-fav="${esc(x.id)}">★</button></div></div>`}

function availablePractice(){if(!coursePack)return[];let q=coursePack.practice;if(currentLesson!=='all'&&currentLesson!=='lesson-13')return[];if(practiceFilter==='smart'){const bad=new Set(local.mistakes.map(m=>m.tag));const weak=q.filter(x=>bad.has(x.tag));return weak.length>=3?weak:q}if(practiceFilter==='mistakes'){const ids=new Set(local.mistakes.map(m=>m.questionId));return q.filter(x=>ids.has(x.id))}return q.filter(x=>x.tag===practiceFilter)}
function resetPractice(){practiceQueue=shuffle(availablePractice());practiceIndex=0;practiceAnswered=false}
function renderPractice(){const el=document.getElementById('view-practice');if(!coursePack||currentLesson!=='lesson-13'&&currentLesson!=='all'){el.innerHTML='<div class="empty">Interactive practice is currently built for Lesson 13. More lesson packs can use the same engine later.</div>';return}if(!practiceQueue.length)resetPractice();const filters=[['smart','Smart mix'],['phone','Phone'],['body','Body'],['g13-1','G13.1'],['g13-2','G13.2'],['g13-3','G13.3'],['g13-4','G13.4'],['g13-5','G13.5'],['mistakes','Mistakes']];el.innerHTML=`<div class="practice-head"><div class="chip-row">${filters.map(([k,n])=>`<button class="chip ${practiceFilter===k?'active':''}" data-pfilter="${k}">${n}</button>`).join('')}</div><div class="practice-progress" id="practiceProgress"></div></div><div class="practice-card" id="practiceCard"></div>`;el.querySelectorAll('[data-pfilter]').forEach(b=>b.onclick=()=>{practiceFilter=b.dataset.pfilter;resetPractice();renderPractice()});renderPracticeQuestion()}
function renderPracticeQuestion(){const box=document.getElementById('practiceCard'),prog=document.getElementById('practiceProgress');if(!box)return;if(!practiceQueue.length){box.innerHTML='<div class="empty">No questions in this set yet.</div>';prog.textContent='';return}const q=practiceQueue[practiceIndex%practiceQueue.length];practiceAnswered=false;prog.textContent=`${practiceIndex+1} / ${practiceQueue.length}`;box.innerHTML=questionHtml(q,'practice');bindQuestion(box,q,'practice')}
function questionHtml(q,mode){const controls=q.type==='mcq'?`<div class="options">${q.choices.map((c,i)=>`<button class="option" data-choice="${i}">${esc(c)}</button>`).join('')}</div>`:`<div style="display:flex;gap:8px"><input class="answer-input" id="${mode}Input" placeholder="Type your answer"><button class="btn primary" id="${mode}Submit">Check</button></div>`;return `<div class="question-kicker">${esc(tagName(q.tag))}</div><div class="question">${esc(q.prompt)}</div>${controls}<div id="${mode}Feedback"></div>`}
function bindQuestion(box,q,mode){if(q.type==='mcq')box.querySelectorAll('[data-choice]').forEach((b,i)=>b.onclick=()=>checkQuestion(q,q.choices[i],mode,b));else{const input=document.getElementById(`${mode}Input`),submit=document.getElementById(`${mode}Submit`);submit.onclick=()=>checkQuestion(q,input.value,mode,null);input.onkeydown=e=>{if(e.key==='Enter')submit.click()}}}
function isCorrect(q,answer){if(q.type==='mcq')return answer===q.answer;return (q.answers||[q.answer]).some(a=>normalizeAnswer(a)===normalizeAnswer(answer))}
function checkQuestion(q,userAnswer,mode,clicked){if((mode==='practice'&&practiceAnswered)||(mode==='quiz'&&quizAnswered))return;const correct=isCorrect(q,userAnswer);if(mode==='practice')practiceAnswered=true;else quizAnswered=true;if(correct){if(mode==='quiz')quizScore++;resolveMistake(q.id)}else recordMistake(q,userAnswer);recordAttempt(q,correct);logActivity(mode);const root=document.getElementById(mode==='practice'?'practiceCard':'quizCard');if(q.type==='mcq')root.querySelectorAll('[data-choice]').forEach(b=>{const val=q.choices[+b.dataset.choice];if(val===q.answer)b.classList.add('correct');if(b===clicked&&!correct)b.classList.add('wrong');b.disabled=true});const f=document.getElementById(`${mode}Feedback`),correctText=q.displayAnswer||q.answer;f.innerHTML=`<div class="feedback-box"><b>${correct?'Correct.':'Not quite.'}</b>${!correct?`<div style="margin-top:5px">Correct answer: <b>${esc(correctText)}</b></div>`:''}<div style="margin-top:6px"><b>Why:</b> ${esc(q.why||'Review the related pattern and try again.')}</div><div class="confidence"><span>How sure were you?</span><button class="btn ghost" data-confidence="guess">Guess</button><button class="btn ghost" data-confidence="unsure">Unsure</button><button class="btn ghost" data-confidence="confident">Confident</button></div><button class="btn primary" style="margin-top:10px" id="${mode}Next">${mode==='quiz'&&quizIndex>=quizQueue.length-1?'See result':'Next'}</button></div>`;f.querySelectorAll('[data-confidence]').forEach(b=>b.onclick=()=>{recordConfidence(q,b.dataset.confidence);f.querySelectorAll('[data-confidence]').forEach(x=>x.disabled=true);b.textContent='Saved ✓'});document.getElementById(`${mode}Next`).onclick=()=>{if(mode==='practice'){practiceIndex=(practiceIndex+1)%practiceQueue.length;renderPracticeQuestion()}else{quizIndex++;if(quizIndex>=quizQueue.length)renderQuizResult();else renderQuizQuestion()}}}
function recordAttempt(q,correct){const a=local.attempts[q.id]||{correct:0,wrong:0,confidence:{guess:0,unsure:0,confident:0}};a[correct?'correct':'wrong']++;a.last=Date.now();local.attempts[q.id]=a;writeJSON(KEYS.local,local)}
function recordConfidence(q,c){const a=local.attempts[q.id]||{correct:0,wrong:0,confidence:{guess:0,unsure:0,confident:0}};if(!a.confidence)a.confidence={guess:0,unsure:0,confident:0};a.confidence[c]=(a.confidence[c]||0)+1;local.attempts[q.id]=a;writeJSON(KEYS.local,local)}
function recordMistake(q,userAnswer){const old=local.mistakes.find(m=>m.questionId===q.id);if(old){old.count++;old.lastWrong=Date.now();old.userAnswer=String(userAnswer)}else local.mistakes.push({id:uid(),questionId:q.id,tag:q.tag,prompt:q.prompt,userAnswer:String(userAnswer),correct:q.displayAnswer||q.answer,why:q.why,count:1,lastWrong:Date.now()});writeJSON(KEYS.local,local)}
function resolveMistake(id){const m=local.mistakes.find(x=>x.questionId===id);if(m)m.recovered=(m.recovered||0)+1;writeJSON(KEYS.local,local)}

function renderQuiz(){const el=document.getElementById('view-quiz');if(!coursePack||currentLesson!=='lesson-13'&&currentLesson!=='all'){el.innerHTML='<div class="empty">Lesson 13 currently has the full quiz engine. Other lessons can be added to the same format next.</div>';return}el.innerHTML=`<div class="practice-head"><div class="chip-row">${[['all','Mixed'],['phone','Phone'],['body','Body'],['grammar','Grammar']].map(([k,n])=>`<button class="chip ${quizFilter===k?'active':''}" data-qfilter="${k}">${n}</button>`).join('')}</div><button class="btn ghost" id="newQuizBtn">New 10-question quiz</button></div><div class="quiz-card" id="quizCard"></div>`;el.querySelectorAll('[data-qfilter]').forEach(b=>b.onclick=()=>{quizFilter=b.dataset.qfilter;startQuiz();renderQuiz()});document.getElementById('newQuizBtn').onclick=()=>{startQuiz();renderQuizQuestion()};if(!quizQueue.length||quizIndex>=quizQueue.length)startQuiz();renderQuizQuestion()}
function quizSource(){let q=coursePack.practice;if(quizFilter==='phone')q=q.filter(x=>x.tag==='phone');if(quizFilter==='body')q=q.filter(x=>x.tag==='body');if(quizFilter==='grammar')q=q.filter(x=>x.tag.startsWith('g13-'));return q}
function startQuiz(){quizQueue=shuffle(quizSource()).slice(0,Math.min(10,quizSource().length));quizIndex=0;quizScore=0;quizAnswered=false}
function renderQuizQuestion(){const box=document.getElementById('quizCard');if(!box)return;if(!quizQueue.length){box.innerHTML='<div class="empty">No questions available for this filter.</div>';return}if(quizIndex>=quizQueue.length){renderQuizResult();return}const q=quizQueue[quizIndex];quizAnswered=false;box.innerHTML=`<div class="practice-progress">Question ${quizIndex+1} / ${quizQueue.length} · Score ${quizScore}</div>${questionHtml(q,'quiz')}`;bindQuestion(box,q,'quiz')}
function renderQuizResult(){const box=document.getElementById('quizCard');const pct=quizQueue.length?Math.round(quizScore/quizQueue.length*100):0;box.innerHTML=`<div class="question-kicker">Quiz complete</div><div class="stat-value">${quizScore}/${quizQueue.length}</div><div class="muted">${pct}% · incorrect answers were added to Mistakes.</div><div style="display:flex;gap:8px;margin-top:14px"><button class="btn primary" id="quizAgain">Try another</button><button class="btn ghost" id="quizMistakes">Review mistakes</button></div>`;document.getElementById('quizAgain').onclick=()=>{startQuiz();renderQuizQuestion()};document.getElementById('quizMistakes').onclick=()=>switchView('mistakes')}

function reviewPool(){const p=currentPool();return[...p.vocab.map(x=>({...x,_type:'v'})),...p.grammar.map(x=>({...x,_type:'g'}))]}
function renderReview(){const el=document.getElementById('view-review');const pool=reviewPool();reviewQueue=reviewMode==='srs'?pool.filter(x=>isDue(x.id)):pool;if(reviewIndex>=reviewQueue.length)reviewIndex=0;el.innerHTML=`<div class="flash-wrap"><div class="chip-row"><button class="chip ${reviewMode==='srs'?'active':''}" id="modeSrs">Due today</button><button class="chip ${reviewMode==='browse'?'active':''}" id="modeBrowse">Browse all</button></div><div class="muted" id="reviewProgress"></div><div class="flash" id="flash"><div class="flash-inner"><div class="face front" id="frontFace"></div><div class="face back" id="backFace"></div></div></div><div class="rate-row" id="rateRow"></div><div class="review-nav" id="reviewNav"></div></div>`;document.getElementById('modeSrs').onclick=()=>{reviewMode='srs';reviewIndex=0;renderReview()};document.getElementById('modeBrowse').onclick=()=>{reviewMode='browse';reviewIndex=0;renderReview()};renderCard()}
function renderCard(){const f=document.getElementById('frontFace'),b=document.getElementById('backFace'),prog=document.getElementById('reviewProgress'),rate=document.getElementById('rateRow'),nav=document.getElementById('reviewNav');if(!reviewQueue.length){f.innerHTML='<div class="big">Nothing due</div><div class="small">Switch to Browse all or choose another lesson.</div>';b.innerHTML='';prog.textContent='0 cards';rate.innerHTML='';nav.innerHTML='';return}const c=reviewQueue[reviewIndex];prog.textContent=`${reviewIndex+1} / ${reviewQueue.length}`;if(c._type==='v'){f.innerHTML=`<div class="big">${esc(c.korean)}</div><div class="small">${esc(c.pos||'Vocabulary')}</div>`;b.innerHTML=`<div class="big" style="font-size:20px">${esc(c.meaning)}</div>${c.example?`<div class="example">${esc(oneExample(c.example))}</div>`:''}`}else{f.innerHTML=`<div class="big" style="font-size:23px">${esc(c.pattern)}</div><div class="small">Tap to reveal the explanation</div>`;b.innerHTML=`<div style="font-size:15px;line-height:1.6">${esc(c.explain)}</div>${c.contrast?`<div class="compare-box">${esc(c.contrast)}</div>`:''}`};const flash=document.getElementById('flash');flash.classList.remove('flipped');flash.onclick=()=>flash.classList.toggle('flipped');if(reviewMode==='srs'){rate.innerHTML=`<button class="btn again" data-rate="again">Again</button><button class="btn hard" data-rate="hard">Hard</button><button class="btn good" data-rate="good">Good</button><button class="btn easy" data-rate="easy">Easy</button>`;rate.querySelectorAll('[data-rate]').forEach(btn=>btn.onclick=()=>rateCard(btn.dataset.rate));nav.innerHTML=''}else{rate.innerHTML='';nav.innerHTML=`<button class="btn ghost" id="prevCard">← Previous</button><button class="btn ghost" id="nextCard">Next →</button>`;document.getElementById('prevCard').onclick=()=>{reviewIndex=(reviewIndex-1+reviewQueue.length)%reviewQueue.length;renderCard()};document.getElementById('nextCard').onclick=()=>{reviewIndex=(reviewIndex+1)%reviewQueue.length;renderCard()}}}
function rateCard(kind){const c=reviewQueue[reviewIndex],p=progressFor(c.id);if(kind==='again'){p.reps=0;p.interval=0;p.due=today()}if(kind==='hard'){p.reps++;p.interval=Math.max(1,Math.round((p.interval||1)*1.2));p.ease=Math.max(1.3,p.ease-.15);p.due=addDays(p.interval)}if(kind==='good'){p.reps++;p.interval=p.reps===1?1:p.reps===2?3:Math.max(3,Math.round(p.interval*p.ease));p.due=addDays(p.interval)}if(kind==='easy'){p.reps++;p.ease+=.15;p.interval=p.reps===1?4:Math.max(5,Math.round((p.interval||2)*p.ease*1.25));p.due=addDays(p.interval)}local.progress[c.id]=p;writeJSON(KEYS.local,local);logActivity('flashcard');reviewQueue.splice(reviewIndex,1);if(reviewIndex>=reviewQueue.length)reviewIndex=0;renderCard()}

function renderMistakes(){const el=document.getElementById('view-mistakes');const arr=[...local.mistakes].sort((a,b)=>b.lastWrong-a.lastWrong);el.innerHTML=`<div class="section-title"><h2>${arr.length} mistake${arr.length===1?'':'s'} to learn from</h2>${arr.length?'<button class="btn primary grow" id="practiceMistakes">Practice these</button>':''}</div>${arr.length?`<div class="mistake-list">${arr.map(m=>`<div class="mistake-item"><div class="mistake-top"><b>${esc(m.prompt)}</b><span class="mistake-tag">${esc(tagName(m.tag))} · ×${m.count}</span></div><div class="mistake-answer">Your last answer: ${esc(m.userAnswer||'—')}<br>Correct: <b>${esc(m.correct||'')}</b></div><div class="feedback-box"><b>Why:</b> ${esc(m.why||'Review this concept and try it again.')}</div></div>`).join('')}</div>`:'<div class="empty">Nothing here yet. Wrong answers from Practice and Quiz will appear here automatically.</div>'}`;if(arr.length)document.getElementById('practiceMistakes').onclick=()=>{practiceFilter='mistakes';resetPractice();switchView('practice')}}

function renderBasics(){const el=document.getElementById('view-basics');el.innerHTML=`<div class="basics-grid">${BASICS.map(b=>`<div class="basic-card"><h3>${esc(b.title)}</h3><b style="font-size:12px">${esc(b.short)}</b><p>${esc(b.body)}</p><div class="formula">${esc(b.formula)}</div></div>`).join('')}<div class="basic-card"><h3>Hangul block builder</h3><p>Choose an initial consonant, vowel, and optional final consonant.</p><div class="composer"><select id="cho"></select><select id="jung"></select><select id="jong"></select></div><div class="syllable-result" id="syllable">가</div><div class="muted" style="text-align:center">초성 + 중성 (+ 종성)</div></div></div>`;setupHangulBuilder()}
function renderQa(){const el=document.getElementById('view-qa'),verified=verificationRegister?.verifiedItems||[],sources=verificationRegister?.sources||[],systems=systemMap?.systems||[],concepts=conceptRegistry?.concepts||[],mappings=conceptCrosswalk?.mappings||[];const byLesson=verified.reduce((m,item)=>{m[item.lessonId]=(m[item.lessonId]||0)+1;return m},{});const lessonCards=coursePacks.map(pack=>{const l=pack.lesson||{},qa=pack.sourcePolicy?.enrichmentQa||{},verifiedIds=qa.verifiedItemIds||[];return `<article class="qa-lesson-card"><div class="qa-vocab-top"><b>Lesson ${esc(l.number||'')}</b><span class="qa-badge verified">${verifiedIds.length} verified</span></div><h3>${esc(l.titleKo||'')} <span class="muted">${esc(l.titleEn||'')}</span></h3><p>${esc(l.theme||'')}</p><div class="muted">${(pack.vocabulary||[]).length} vocab · ${(pack.grammar||[]).length} grammar · ${(pack.practice||[]).length} practice</div></article>`}).join('');el.innerHTML=`<div class="qa-hero"><div class="lesson-eyebrow">Live from GitHub content JSON</div><h2>Lesson 1-14 Content Architecture</h2><p>Teacher PPT-derived course data now loads on this site. Hanja, Chinese glosses, and word-origin help are shown as enrichment, with verified items traced to named references.</p></div>
<div class="qa-stat-grid"><div class="stat-card"><div class="stat-value">${coursePacks.length}</div><div class="stat-label">structured lesson packs</div></div><div class="stat-card"><div class="stat-value">${verified.length}</div><div class="stat-label">verified enrichment records</div></div><div class="stat-card"><div class="stat-value">${concepts.length}</div><div class="stat-label">canonical concepts</div></div><div class="stat-card"><div class="stat-value">${systems.length}</div><div class="stat-label">cross-lesson systems</div></div></div>
<div class="section-title"><h2>Source Boundaries</h2></div><div class="source-boundary"><div><b>Teacher source</b><p>Lesson goals, classroom vocabulary, grammar sequence, and PPT slide references stay in the lesson packs.</p></div><div><b>Verified enrichment</b><p>Selected Hanja, Chinese glosses, and origin types are promoted only when they appear in this register.</p></div><div><b>Unverified enrichment</b><p>Remaining Hanja, Chinese gloss, originType, and originNote fields remain learner aids until checked.</p></div></div>
<div class="section-title"><h2>Reference Sources</h2></div><div class="qa-source-grid">${sources.map(s=>`<a class="qa-source-card" href="${esc(s.url)}" target="_blank" rel="noopener"><b>${esc(s.label)}</b><span>${esc(s.type)}</span><small>${esc((s.usedFor||[]).join(', '))}</small></a>`).join('')}</div>
<div class="section-title"><h2>Lesson Packs</h2><span class="muted">Click a lesson in the sidebar to inspect it.</span></div><div class="qa-lesson-grid">${lessonCards}</div>
<div class="section-title"><h2>Verified Enrichment Register</h2><span class="muted">${verified.length} item-level records</span></div><div class="qa-register">${verified.map(item=>`<article class="qa-register-row"><div><b>${esc(item.korean)}</b><span class="entry-meta">${esc(item.lessonId)} · ${esc(item.itemId)}</span></div><div>${esc(item.values?.hanja||'')} ${item.values?.meaningZh?`· ${esc(item.values.meaningZh)}`:''}</div><div class="muted">${esc((item.verifiedFields||[]).join(', '))}</div></article>`).join('')}</div>
<div class="section-title"><h2>System Map</h2><span class="muted">${mappings.length} grammar crosswalk mappings</span></div><div class="system-grid">${systems.slice(0,8).map(s=>`<article class="system-card"><h3>${esc(s.title)}</h3><p>${esc((s.lessonProgression||[]).map(x=>`L${x.lesson}`).join(' → '))}</p></article>`).join('')}</div>`}
function setupHangulBuilder(){const cho=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'],jung=['ㅏ','ㅐ','ㅑ','ㅒ','ㅓ','ㅔ','ㅕ','ㅖ','ㅗ','ㅘ','ㅙ','ㅚ','ㅛ','ㅜ','ㅝ','ㅞ','ㅟ','ㅠ','ㅡ','ㅢ','ㅣ'],jong=['','ㄱ','ㄲ','ㄳ','ㄴ','ㄵ','ㄶ','ㄷ','ㄹ','ㄺ','ㄻ','ㄼ','ㄽ','ㄾ','ㄿ','ㅀ','ㅁ','ㅂ','ㅄ','ㅅ','ㅆ','ㅇ','ㅈ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];const fill=(id,a)=>{document.getElementById(id).innerHTML=a.map((x,i)=>`<option value="${i}">${x||'no final'}</option>`).join('')};fill('cho',cho);fill('jung',jung);fill('jong',jong);const update=()=>{const a=+document.getElementById('cho').value,b=+document.getElementById('jung').value,c=+document.getElementById('jong').value;document.getElementById('syllable').textContent=String.fromCharCode(0xAC00+(a*21+b)*28+c)};['cho','jung','jong'].forEach(id=>document.getElementById(id).onchange=update);update()}

function openModal(html){document.getElementById('modal').innerHTML=html;document.getElementById('modalBg').classList.add('open');document.getElementById('modalBg').setAttribute('aria-hidden','false')}
function closeModal(){document.getElementById('modalBg').classList.remove('open');document.getElementById('modalBg').setAttribute('aria-hidden','true')}
document.getElementById('modalBg').onclick=e=>{if(e.target.id==='modalBg')closeModal()}
function bindModalClose(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}

document.getElementById('appearanceBtn').onclick=()=>{openModal(`<h2>Appearance</h2><p class="muted">Choose a preset. Your choice stays in this browser.</p><div class="theme-presets">${Object.entries(THEMES).map(([k,t])=>`<button class="theme-swatch" data-theme="${k}" style="background:linear-gradient(135deg,${t.bg} 50%,${t.accent} 50%)" title="${t.name}"></button>`).join('')}</div><div class="modal-actions"><button class="btn ghost" data-close>Close</button></div>`);document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{themeState={preset:b.dataset.theme,custom:null};writeJSON(KEYS.theme,themeState);applyTheme()});bindModalClose()}
document.getElementById('globalSearchBtn').onclick=()=>{openModal(`<h2>Search everything</h2><input id="globalSearch" placeholder="학교, phone, obligation, 學校…"><div class="search-results" id="searchResults"></div><div class="modal-actions"><button class="btn ghost" data-close>Close</button></div>`);const input=document.getElementById('globalSearch'),results=document.getElementById('searchResults');input.oninput=()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='';return}const items=[...allVocab.map(x=>({title:x.korean,sub:[x.meaning,x.meaningZh,x.hanja,x.originType].filter(Boolean).join(' · '),type:'Vocabulary'})),...allGrammar.map(x=>({title:x.pattern,sub:x.explain,type:'Grammar'}))].filter(x=>(x.title+' '+x.sub).toLowerCase().includes(q)).slice(0,30);results.innerHTML=items.map(x=>`<div class="search-result"><b>${esc(x.title)}</b><div class="muted">${esc(x.type)} · ${esc(x.sub)}</div></div>`).join('')||'<div class="empty">No matches.</div>'};input.focus();bindModalClose()}
document.getElementById('importBtn').onclick=()=>{openModal(`<h2>Backup / restore</h2><p class="muted">This handles your personal progress, favorites, mistakes, and feedback. Course content stays separate.</p><div style="display:flex;gap:8px"><button class="btn primary" id="exportData">Export JSON</button><label class="btn ghost">Import JSON<input hidden type="file" id="importData" accept="application/json"></label></div><div class="modal-actions"><button class="btn ghost" data-close>Close</button></div>`);document.getElementById('exportData').onclick=()=>{const blob=new Blob([JSON.stringify(local,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='korean-review-progress.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{local={...local,...JSON.parse(r.result)};writeJSON(KEYS.local,local);closeModal();renderAll()}catch{alert('Invalid backup file.')}};r.readAsText(f)};bindModalClose()}
document.getElementById('feedbackBtn').onclick=()=>{openModal(`<h2>Something confusing?</h2><p class="muted">This prototype stores feedback in your browser so we can use it during HCI iteration.</p><label>What happened?</label><select id="feedbackType"><option>I couldn't find something</option><option>I didn't understand a question</option><option>I didn't know what a button did</option><option>This page felt overwhelming</option><option>Something is broken</option><option>Other</option></select><label>Tell us more</label><textarea id="feedbackText" placeholder="What were you trying to do?"></textarea><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="saveFeedback">Save feedback</button></div>`);document.getElementById('saveFeedback').onclick=()=>{local.feedback.push({type:document.getElementById('feedbackType').value,text:document.getElementById('feedbackText').value.trim(),view:currentView,lesson:currentLesson,ts:Date.now()});writeJSON(KEYS.local,local);closeModal()};bindModalClose()}
document.getElementById('settingsBtn').onclick=()=>{openModal(`<h2>Advanced content sources</h2><p class="muted">Lesson 1-14 structured packs and the enrichment verification register now live in this GitHub repository. These Google Sheet links remain available for optional shared class vocabulary and grammar.</p><label>Lessons CSV URL</label><input id="cfgLessons" value="${esc(config.lessons)}"><label>Vocabulary CSV URL</label><input id="cfgVocab" value="${esc(config.vocab)}"><label>Grammar CSV URL</label><input id="cfgGrammar" value="${esc(config.grammar)}"><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="saveCfg">Save & reload</button></div>`);document.getElementById('saveCfg').onclick=()=>{config={lessons:document.getElementById('cfgLessons').value.trim(),vocab:document.getElementById('cfgVocab').value.trim(),grammar:document.getElementById('cfgGrammar').value.trim()};writeJSON(KEYS.config,config);closeModal();loadContent()};bindModalClose()}

loadContent();
